run-name: "Building release ${{ github.ref }}"

on:
  release:
    types:
      - created
      - edited

jobs:
  release:
    name: Add Assets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --verbose --target x86_64-unknown-linux-musl
      # - name: FindBinary
      #   run: find . -type f -name 'jfswatch' -executable -print
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/jfswatch

      # - name: Compile
      #   id: compile
      #   uses: rust-build/rust-build.action@v1.4.4
      #   with:
      #     RUSTTARGET: x86_64-unknown-linux-musl
      #                 # x86_64-pc-windows-gnu
      #                 # wasm32-wasi
      #                 # x86_64-apple-darwin
      #     TOOLCHAIN_VERSION: stable
      #     UPLOAD_MODE: none
